Monitoria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('meuapp.urls'))
]

meuapp/urls.py
from django.urls import path, include
from . import views

app_name = 'meuapp'

urlpatterns = [
    path('exemplo/', views.SightView.as_view(), name="novoapp"),
]

meuapp/models.py
from django.db import models

# Create your models here.

meuapp/views.py
from django.shortcuts import render
from django.views import View
from django.http import HttpResponse

# Create your views here.

class SightView(View):
    def get(self, request):
        
        ctx = {
            'user': 'Paulo'
            }
        return render(request, 'teste.html', ctx)
    
    def post(self, request):
        nome = request.POST.get("inputizinho")
        print(nome)
        return HttpResponse("texto")

meuapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        button {
            width: 100px;
            height: 200px;
        }
    </style>
</head>
<body>
    <h1>Boa tarde, {{user}}</h1>
    <form action="{% url 'meuapp:novoapp' %}" method="POST">
        {% csrf_token %}
        <label for="inputizinho">MEU INPUT</label>
        <input type="text" name="inputizinho" id="meuinput">
        <button type="submit"></button>
    </form>
    {% block content %}{% endblock content %}
</body>
</html>

meuapp/templates/teste.html
{% extends 'base.html' %}

{% block content %}
    <h1>esse é o filho</h1>
{% endblock content %}